version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis
  web:
    environment:
      SERVER_NAME: web
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/site-usage-crawler
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  sidekiq:
    environment:
      SERVER_NAME: sidekiq
    build: .
    command: bundle exec sidekiq -e development
    volumes:
      - .:/site-usage-crawler
    depends_on:
      - db
      - redis
