default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: site_usage_development

test:
  <<: *default
  database: site_usage_test

# production:
#   <<: *default
#   database: db/production.sqlite3
